/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package SipFinal;

import java.awt.Label;

/**
 *
 * @author satria
 */
public class NewJInternalFrame1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame1
     */
    public NewJInternalFrame1() {
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        jLabel1.setText("""
                <html><body>Price<br>
                Rice standard       = 4000 or 6000<br>
                Fried Tempe         = 1000<br>
                Omelette            = 3000<br>
                Sunny-side up egg   = 3000<br>
                Spinach and Corn    = 4000 or 6000<br>
                Vegetable Macaroni  = 4000 or 6000 <br><br><br>
                        
                        
                Countable Menu: Fried Tempe, Omelette, Sunny-side up egg.<br>
                Uncountable Menu: Rice, Spinach and Corn, Vegetable Macaroni. <br><br><br>
                
                
                Note:<br>
                Large portion price is 150% standard portion price<br>
                There is no update and add menu feature available yet<br>
                There is no update price feature available yet<br>
                <html><body>
                """
                );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("INFO");

        jLabel1.setText("label1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setPreferredSize(new java.awt.Dimension(212, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
