/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package SipFinal;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author satria
 */
public class NewJInternalFrame0 extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame0
     */
    
    
    public NewJInternalFrame0() {
         // Customization and initialization code here
        initComponents();
        
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        String labelValue = labelPriceRice.getText();
        if (labelValue.isEmpty()) {
            labelPriceRice.setText("4000");
            labelPriceTempe.setText("1000");
            labelPriceTdadar.setText("3000");
            labelPriceTceplok.setText("3000");
            labelPriceBayamJ.setText("4000");
            labelPriceSayurM.setText("4000");
        }
        labelPriceRice.setVisible(false);
        labelPriceTempe.setVisible(false);
        labelPriceTdadar.setVisible(false);
        labelPriceTceplok.setVisible(false);
        labelPriceBayamJ.setVisible(false);
        labelPriceSayurM.setVisible(false);
        
        
        
        
        showDialog();
        
        
    }
    
    private void showDialog() {
            // Create the dialog components
        JTextField textField = new JTextField();
        Object[] message = {" CASHIER APP\n for buffet-style restaurant\n\nEnter your name:\n", textField};

          // Show the dialog
        int option = JOptionPane.showOptionDialog(this, message, "CASHIER APP",
             JOptionPane.DEFAULT_OPTION,
             JOptionPane.QUESTION_MESSAGE,
             null, null, null);
        String input = textField.getText();

          jTextField1.setText("Good Luck, " + input);

    }
   
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelTceplok = new javax.swing.JLabel();
        spinnerTelurC = new javax.swing.JSpinner();
        labelTdadar = new javax.swing.JLabel();
        labelTempe = new javax.swing.JLabel();
        labelPriceTempe = new javax.swing.JLabel();
        labelRice = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        comboRice = new javax.swing.JComboBox<>();
        labelPriceTdadar = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        spinnerTempeG = new javax.swing.JSpinner();
        labelPriceTceplok = new javax.swing.JLabel();
        checkSayurM = new javax.swing.JCheckBox();
        spinnerTelurD = new javax.swing.JSpinner();
        comboSayurM = new javax.swing.JComboBox<>();
        labelPriceBayamJ = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelPriceSayurM = new javax.swing.JLabel();
        checkBayamJ = new javax.swing.JCheckBox();
        labelPriceRice = new javax.swing.JLabel();
        comboBayamJ = new javax.swing.JComboBox<>();
        labelTitle = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        spinnerBayamJ = new javax.swing.JSpinner();
        spinnerSayurM = new javax.swing.JSpinner();

        setClosable(true);
        setTitle("CASHIER");

        jTabbedPane1.setName(""); // NOI18N

        labelTceplok.setText("sunny-side up egg");

        spinnerTelurC.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinnerTelurC.setToolTipText("");

        labelTdadar.setText("Omelette");

        labelTempe.setText("Fried Tempeh");

        labelRice.setText("Rice");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Dine in");
        jRadioButton1.setActionCommand(jRadioButton1.getText());
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        comboRice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Standard", "Large" }));
        comboRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRiceActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Takeaway");
        jRadioButton2.setActionCommand(jRadioButton2.getText());
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        spinnerTempeG.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        checkSayurM.setText("Vegetable Macaroni");
        checkSayurM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSayurMActionPerformed(evt);
            }
        });

        spinnerTelurD.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        comboSayurM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Large" }));
        comboSayurM.setEnabled(false);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        checkBayamJ.setText("Spinach and Corn");
        checkBayamJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBayamJActionPerformed(evt);
            }
        });

        comboBayamJ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Large" }));
        comboBayamJ.setEnabled(false);
        comboBayamJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBayamJActionPerformed(evt);
            }
        });

        labelTitle.setText("CASH REGISTER");

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jTextField1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        spinnerBayamJ.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spinnerBayamJ.setToolTipText("");
        spinnerBayamJ.setEnabled(false);

        spinnerSayurM.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spinnerSayurM.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2))
                    .addComponent(checkSayurM)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBayamJ)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTempe)
                                    .addComponent(labelTdadar)
                                    .addComponent(labelTceplok)
                                    .addComponent(labelRice)))
                            .addComponent(labelTitle))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spinnerTempeG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(labelPriceTempe))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboBayamJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPriceBayamJ)
                                    .addComponent(spinnerBayamJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboSayurM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spinnerSayurM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPriceSayurM))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spinnerTelurC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPriceTceplok))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spinnerTelurD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPriceTdadar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboRice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPriceRice)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitle)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboRice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelRice))
                    .addComponent(labelPriceRice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerTempeG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTempe)
                    .addComponent(labelPriceTempe))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerTelurD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTdadar)
                    .addComponent(labelPriceTdadar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerTelurC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTceplok)
                    .addComponent(labelPriceTceplok))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBayamJ)
                    .addComponent(comboBayamJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPriceBayamJ)
                    .addComponent(spinnerBayamJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSayurM)
                    .addComponent(comboSayurM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPriceSayurM)
                    .addComponent(spinnerSayurM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        String diningOption = "Dine in";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void comboRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRiceActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        String diningOption = "Takeaway";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void checkSayurMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSayurMActionPerformed
        // TODO add your handling code here:
        boolean selected = checkSayurM.isSelected();
        comboSayurM.setEnabled(selected);
        spinnerSayurM.setEnabled(selected);
    }//GEN-LAST:event_checkSayurMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int totalTCMP = 0;
        int totalTUMP = 0;
        int totalTCMT = 0;
        int totalTUMT = 0;

        int priceRice = Integer.parseInt(labelPriceRice.getText());
        int priceTempe = Integer.parseInt(labelPriceTempe.getText());
        int priceTdadar = Integer.parseInt(labelPriceTdadar.getText());
        int priceTceplok = Integer.parseInt(labelPriceTceplok.getText());
        int priceBayamJ = Integer.parseInt(labelPriceBayamJ.getText());
        int priceSayurM = Integer.parseInt(labelPriceSayurM.getText());

        String selectedRice = (String) comboRice.getSelectedItem();
        switch(selectedRice) {
            case "Standard" :
            totalTUMP += priceRice;
            totalTUMT += 1;
            break;
            case "Large" :
            totalTUMP += priceRice * 1.5;
            totalTUMT += 1;
            break;
        }

        int tempeGoreng = (int) spinnerTempeG.getValue();
        totalTCMT = (tempeGoreng > 0) ? totalTCMT + 1 : totalTCMT;
        totalTCMP += tempeGoreng * priceTempe;

        int telurDadar = (int) spinnerTelurD.getValue();
        totalTCMT = (telurDadar > 0) ? totalTCMT + 1 : totalTCMT;
        totalTCMP += telurDadar * priceTdadar;

        int telurCeplok = (int) spinnerTelurC.getValue();
        totalTCMT = (telurCeplok > 0) ? totalTCMT + 1 : totalTCMT;
        totalTCMP += telurCeplok * priceTceplok;

        if (comboBayamJ.isEnabled()) {
            totalTUMT += 1;
            int bayamJ = (int) spinnerBayamJ.getValue();
            String selectedBayam = (String) comboBayamJ.getSelectedItem();
            switch(selectedBayam) {
                
                case "Standard" :
                totalTUMP += priceBayamJ * bayamJ;
                break;
                
                case "Large" :
                totalTUMP += (priceBayamJ * 1.5) * bayamJ;
                break;
            }
        }

        if (comboSayurM.isEnabled()) {
            totalTUMT += 1;
            int sayurM = (int) spinnerSayurM.getValue();
            String selectedMakaroni = (String) comboSayurM.getSelectedItem();
            switch(selectedMakaroni) {
                
                case "Standard" :
                totalTUMP += priceSayurM * sayurM;
                break;
                
                case "Large" :
                totalTUMP += (priceSayurM * 1.5) * sayurM;
                break;
            }
        }

        int totalPrice = totalTCMP + totalTUMP;
        if (totalPrice == 0) {
            JOptionPane.showMessageDialog(null,
                "Total price is 0. Please check your order.",
                "Alert",
                JOptionPane.WARNING_MESSAGE);
        } else {

            ButtonModel selectedModel = buttonGroup1.getSelection();
            String selectedValue = "";
            if (selectedModel != null){
                selectedValue = selectedModel.getActionCommand();
            }

            JPanel newPanel = new JPanel();
            GridLayout experimentLayout = new GridLayout(7, 2);
            JLabel labelTextdiningO = new JLabel("Dining Option : ");
            JLabel labelResultdiningO = new JLabel(selectedValue);
            JLabel labelTextTCMT = new JLabel("Total Countable Menu Type : ");
            JLabel labelResultTCMT = new JLabel(Integer.toString(totalTCMT));
            JLabel labelTextTCMP = new JLabel("Total Countable Menu Price : ");
            JLabel labelResultTCMP = new JLabel(Integer.toString(totalTCMP));
            JLabel labelTextTUMT = new JLabel("Total Uncountable Menu Type : ");
            JLabel labelResultTUMT = new JLabel(Integer.toString(totalTUMT));
            JLabel labelTextTUMP = new JLabel("Total Uncountable Menu Price : ");
            JLabel labelResultTUMP = new JLabel(Integer.toString(totalTUMP));
            JLabel labelTextTotal = new JLabel("Total Price : ");
            JTextField textFieldresult = new JTextField(Integer.toString(totalPrice));
            textFieldresult.setEnabled(false);
            textFieldresult.setDisabledTextColor(Color.black);
            JButton buttonBack = new JButton("Back");
            JButton buttonDelete = new JButton("Delete");

            // Menambahkan komponen-komponen yang diperlukan ke panel baru
            newPanel.setLayout(experimentLayout); // Set layout ke panel
            newPanel.add(labelTextdiningO);
            newPanel.add(labelResultdiningO);
            newPanel.add(labelTextTCMT);
            newPanel.add(labelResultTCMT);
            newPanel.add(labelTextTCMP);
            newPanel.add(labelResultTCMP);
            newPanel.add(labelTextTUMT);
            newPanel.add(labelResultTUMT);
            newPanel.add(labelTextTUMP);
            newPanel.add(labelResultTUMP);
            newPanel.add(labelTextTotal);
            newPanel.add(textFieldresult);
            newPanel.add(buttonBack);
            newPanel.add(buttonDelete);

            if (jTabbedPane1.getTabCount() == 1) {
                settabCount(1);
            }

            // Menambahkan panel baru ke JTabbedPane
            int tabCount = gettabCount();
            settabCount(tabCount + 1);
            jTabbedPane1.addTab("Cust" + tabCount, newPanel);
            // Mengaktifkan tab baru yang ditambahkan
            jTabbedPane1.setSelectedComponent(newPanel);

            buttonDelete.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Menghapus tab ketika tombol "Delete" ditekan
                    int selectedIndex = jTabbedPane1.getSelectedIndex();
                    if (selectedIndex >= 0) {
                        jTabbedPane1.remove(selectedIndex);
                    }
                }
            });
            
            buttonBack.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Menghapus tab ketika tombol "Delete" ditekan
                    jTabbedPane1.setSelectedIndex(0);
                }
            });
            
            setdefault();
        }
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void setdefault(){
        
        jRadioButton1.setSelected(true);
        comboRice.setSelectedIndex(0);
        comboBayamJ.setSelectedIndex(0);
        comboSayurM.setSelectedIndex(0);
        comboBayamJ.setEnabled(false);
        comboSayurM.setEnabled(false);
        checkBayamJ.setSelected(false);
        checkSayurM.setSelected(false);
        
        spinnerTempeG.setValue(0);
        spinnerTelurC.setValue(0);
        spinnerTelurD.setValue(0);
        spinnerBayamJ.setValue(1);
        spinnerSayurM.setValue(1);
        spinnerBayamJ.setEnabled(false);
        spinnerSayurM.setEnabled(false);

        
        
    }
    
    private void checkBayamJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBayamJActionPerformed
        // TODO add your handling code here:
        boolean selected = checkBayamJ.isSelected();
        comboBayamJ.setEnabled(selected);
        spinnerBayamJ.setEnabled(selected);
    }//GEN-LAST:event_checkBayamJActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void comboBayamJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBayamJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBayamJActionPerformed

    private void settabCount(int x) {
        tabCount = x;
    }
    
    private int gettabCount() {
        return tabCount;
    }
    
    
    private int tabCount = 1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBayamJ;
    private javax.swing.JCheckBox checkSayurM;
    private javax.swing.JComboBox<String> comboBayamJ;
    private javax.swing.JComboBox<String> comboRice;
    private javax.swing.JComboBox<String> comboSayurM;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelPriceBayamJ;
    private javax.swing.JLabel labelPriceRice;
    private javax.swing.JLabel labelPriceSayurM;
    private javax.swing.JLabel labelPriceTceplok;
    private javax.swing.JLabel labelPriceTdadar;
    private javax.swing.JLabel labelPriceTempe;
    private javax.swing.JLabel labelRice;
    private javax.swing.JLabel labelTceplok;
    private javax.swing.JLabel labelTdadar;
    private javax.swing.JLabel labelTempe;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JSpinner spinnerBayamJ;
    private javax.swing.JSpinner spinnerSayurM;
    private javax.swing.JSpinner spinnerTelurC;
    private javax.swing.JSpinner spinnerTelurD;
    private javax.swing.JSpinner spinnerTempeG;
    // End of variables declaration//GEN-END:variables
}
    
